USE pei_edf;

CREATE TABLE Alunos (
	IdAluno INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
	Nome VARCHAR(20) NOT NULL,
	Sobrenome VARCHAR(30) NOT NULL,
	Email VARCHAR(30) NOT NULL,
	Senha VARCHAR(20) NOT NULL,
	NivelAtual INTEGER DEFAULT 1
);
